<a href="https://colab.research.google.com/github/Elwing-Chou/ximen_ai_20260706/blob/main/ximen_20260720.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import urllib.request as req
url = "https://github.com/Elwing-Chou/ximen_ai_20260706/raw/refs/heads/main/titanic/train.csv"
req.urlretrieve(url, "train.csv")
url = "https://github.com/Elwing-Chou/ximen_ai_20260706/raw/refs/heads/main/titanic/test.csv"
req.urlretrieve(url, "test.csv")

('test.csv', <http.client.HTTPMessage at 0x7c028ebcce90>)

In [2]:
import pandas as pd
train_df = pd.read_csv("train.csv", encoding="utf-8")
test_df = pd.read_csv("test.csv", encoding="utf-8")

In [4]:
test_df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

1. 過濾: 保留需要的
2. 轉換: old val -> new val

In [ ]:
demo = test_df.head(3)
# 過濾: 準備跟你的資料筆數依樣多True/False的list裡
fil = [True, False, True]
# 準備好帶入[]
demo[fil]
# 實際上: 你會用操作轉成True, False
# pandas資料型態: DataFrame(表格) Series(1D清單)
# and(&) or(|)
fil_1 = demo["Age"] < 35
fil_2 = demo["Age"] > 60
fil = fil_1 | fil_2
demo[fil]

In [23]:
def func(x):
    if x == "male":
        return 0
    elif x == "female":
        return 1
    else:
        return -1
# Series apply: 一格轉一格
demo["Sex"].apply(func)

0    1
1    0
2    1
Name: Sex, dtype: int64

In [ ]:
# 我懶得分開做處理, 處理x的時候我通常會把我所有資料合併一起做
total_df = pd.concat([train_df, test_df])
total_df = total_df.drop(["PassengerId", "Survived"], axis=1)
total_df

In [ ]:
# Step 0. 資料預處理(pre-processing)
def func(n):
    if pd.isna(n):
        return n
    else:
        return n.split(",")[-1].split(".")[0].strip()

total_df["Name"] = total_df["Name"].apply(func)
total_df

In [ ]:
# unique()/value_counts()
total_df["Name"].value_counts()

In [41]:
dic = total_df["Ticket"].value_counts()
def func(n):
    if pd.isna(n):
        return n
    else:
        return dic[n]
total_df["Ticket"] = total_df["Ticket"].apply(func)

In [44]:
total_df["Cabin"].value_counts()
def func(n):
    if pd.isna(n):
        return n
    else:
        return n[0]
total_df["Cabin"] = total_df["Cabin"].apply(func)

In [45]:
total_df["Cabin"].value_counts()

Cabin
C    94
B    65
D    46
E    41
A    22
F    21
G     5
T     1
Name: count, dtype: int64

In [46]:
total_df

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,Mr,male,22.0,1,0,1,7.2500,NaN,S
1,1,Mrs,female,38.0,1,0,2,71.2833,C,C
2,3,Miss,female,26.0,0,0,1,7.9250,NaN,S
3,1,Mrs,female,35.0,1,0,2,53.1000,C,S
4,3,Mr,male,35.0,0,0,1,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
413,3,Mr,male,NaN,0,0,1,8.0500,NaN,S
414,1,Dona,female,39.0,0,0,3,108.9000,C,C
415,3,Mr,male,38.5,0,0,1,7.2500,NaN,S
416,3,Mr,male,NaN,0,0,1,8.0500,NaN,S
417,3,Master,male,NaN,1,1,3,22.3583,NaN,C